(function(g){var window=this;var moa=function(a){if(!a.Fa||!a.Fa.annotations)return null;a=g.p(a.Fa.annotations);for(var b=a.next();!b.done;b=a.next())if(b=b.value,b.playerAnnotationsExpandedRenderer&&b.playerAnnotationsExpandedRenderer.featuredChannel)return b.playerAnnotationsExpandedRenderer.featuredChannel;return null},q0=function(a){a.i||(a.i=new g.yn,g.H(a,a.i));
return a.i},r0=function(a){a.N("cardstatechange",g.sK(a)&&g.tK(a)?1:0)},noa=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Ri&&a.dataset){if(g.jc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.ed("pollChoiceIndex"))},ooa=function(a){return Math.pow(a,3)},poa=function(a){return 3*a*a-2*a*a*a},s0=function(a,b){(0,g.z)(b,function(c){c={csn:a,
ve:g.zA(c),eventType:4};var d={Vi:void 0,jh:a};"UNDEFINED_CSN"==a?g.KA("visualElementShown",c,d):g.rr("visualElementShown",c,g.wr,d)})},t0=function(a,b){(0,g.z)(b,function(c){var d=void 0;
d=void 0===d?!1:d;c={csn:a,ve:g.zA(c),eventType:d?16:8};d={Vi:void 0,jh:a,xB:d};"UNDEFINED_CSN"==a?g.KA("visualElementHidden",c,d):g.rr("visualElementHidden",c,g.wr,d)})},w0=function(a){a=g.Qa(a);
delete u0[a];g.Zb(u0)&&v0&&v0.stop()},x0=function(){v0||(v0=new g.I(function(){qoa()},20));
var a=v0;a.isActive()||a.start()},qoa=function(){var a=(0,g.A)();
g.Mb(u0,function(b){y0(b,a)});
g.Zb(u0)||x0()},z0=function(a,b,c,d){g.nn.call(this);
if(!g.La(a)||!g.La(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.l=a;this.G=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.D=0;this.B=null},y0=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.D=1E3/(b-a.B);a.B=b;A0(a,a.progress);1==a.progress?(a.g=0,w0(a),a.Xc(),a.o()):1==a.g&&a.Mq()},A0=function(a,b){g.Na(a.C)&&(b=a.C(b));
a.coords=Array(a.l.length);for(var c=0;c<a.l.length;c++)a.coords[c]=(a.G[c]-a.l[c])*b+a.l[c]},B0=function(a,b){g.Zj.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.D;this.state=b.g},C0=function(a,b,c,d,e){z0.call(this,b,c,d,e);
this.element=a},D0=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
C0.call(this,a,b,c,d,e)},E0=function(a){g.E.call(this);
this.i=a||window;this.g=[]},roa=function(a,b,c,d){c=(0,g.x)(c,d||a.i);
b=g.hr(b,"change",c,"iv-card-poll-choice-input");a.g.push(b)},F0=function(a){return a.baseUrl||null},soa=function(a,b,c){function d(Y){var ha=Y.hovercardButton;
if(!ha)return null;ha=ha.subscribeButtonRenderer;if(!ha)return null;var Ha=f(ha.unsubscribedButtonText),md=f(ha.subscribedButtonText);if(ha.subscribed){var Jc=f(ha.subscriberCountWithUnsubscribeText);var dh=f(ha.subscriberCountText)}else Jc=f(ha.subscriberCountText),dh=f(ha.subscriberCountWithSubscribeText);var Ad=null;return Y.signinEndpoint&&(Ad=g.Ub(Y,"signinEndpoint","webNavigationEndpointData","url"),!Ad)?null:Ha&&(md||Ad)?{subscribed:ha.subscribed,subscribeText:Ha,subscribeCount:Jc,unsubscribeText:md,
unsubscribeCount:dh,enabled:ha.enabled,signinUrl:Ad,classic:Y.useClassicSubscribeButton}:null}
function e(Y){if(Y){var ha=[],Ha=Y.videoId;Ha&&ha.push("v="+Ha);(Ha=Y.playlistId)&&ha.push("list="+Ha);(Y=Y.startTimeSeconds)&&ha.push("t="+Y);return"/watch?"+ha.join("&")}}
function f(Y){if(!Y)return null;var ha=Y.simpleText;return ha?ha:Y.runs?(0,g.fe)(Y.runs,function(Ha){return Ha.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,q=null,t=null,v=null,y=null,B=!1,C=null,G=null,L=null,F=null,M=null;if("VIDEO"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,t=f(b.videoDuration);else if("PLAYLIST"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,v=f(b.playlistLength);else if("CHANNEL"==k){if(B=g.Ub(l,"browseEndpoint","browseId"))y=B,m="/channel/"+y;n=!1;q="new";(B=!!b.isSubscribe)?C=d(b):G=f(b.subscribersText)}else"WEBSITE"==
k?((L=g.Ub(l,"urlEndpoint","url"))&&(m=L),n=!0,q="new",L=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==k&&(b.productPrice&&b.additionalFeesText&&(F=f(b.productPrice),M=f(b.additionalFeesText)),(a=g.Ub(l,"urlEndpoint","url"))&&(m=a),n=!0,q="new");a=g.Ub(b,"title","accessibility","accessibilityData","label");return{id:"element-"+c,type:k,title:f(b.title),metadata:f(b.metadata),callToAction:f(b.callToAction),Yt:b.image,iconUrl:L,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),
aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:t,playlistLength:v,channelId:y,subscribeButton:C,subscribersText:G,isSubscribe:B,targetUrl:m,QC:n,Gb:{itct:b.trackingParams},xL:q,Ji:a?a:null,UC:b.isPlaceholder,impressionUrls:(0,g.fe)(b.impressionUrls||[],F0),HC:(0,g.fe)(b.hovercardShowUrls||[],F0),clickUrls:(0,g.fe)(l.loggingUrls||[],F0),visualElement:g.yA(b.trackingParams),productPrice:F,additionalFeesText:M}},G0=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=(0,g.fe)(a.impressionUrls||[],F0);a.trackingParams&&(c.visualElement=g.yA(a.trackingParams));var d=(0,g.fe)(a.elements||[],function(e,f){return soa(b,e,f)});
c.elements=(0,g.Wd)(d,function(e){return!!e});
return c},H0=function(a){g.aP.call(this,a);
this.o=this.i=null;this.g={};this.B={};this.w=this.l=null;this.D=[];a=a.L();this.G=g.Xy(a)||g.Zy(a);this.I=!0;this.C=0;this.u=new g.Qs(this);g.H(this,this.u);this.u.J(this.player,g.AD("creatorendscreen"),this.AD);this.u.J(this.player,"crx_creatorendscreen",this.BD);this.u.J(this.player,"resize",this.Ma);this.u.J(window,"focus",this.wK);this.load();var b=g.Qd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Bi(this,function(){g.Vd(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},I0=function(a){return a.player.getVideoData().ac?"current":a.G?"new":"current"},J0=function(a){return"creator-endscreen-editor"===a.player.L().playerStyle},K0=function(a,b){g.eQ(a.player.app,"creatorendscreen",void 0);
a.l&&(a.l.dispose(),a.l=null,a.w.dispose(),a.w=null);for(var c in a.g)a.g[c].dispose();a.g={};a.B={};0<a.D.length&&(a.D.forEach(function(l){l.dispose()}),a.D.length=0);
a.C=0;if((a.i=b)&&b.elements){toa(a);c=[];var d=new g.xD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.L().g||(a.l=new g.T({A:"div",F:"ytp-ce-shadow"}),g.DK(a.player,a.l.element,4),a.w=new g.pL(a.l,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=uoa(a,e);a.g[e.id]=f;a.B[e.id]=e;g.DK(a.player,f.element,4);var k=new g.xD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);voa(a,f,e)}g.zK(a.player,
c);a.Ma()}},toa=function(a){var b=g.TA(),c=g.UA();
c&&b&&a.i.visualElement&&g.LA(c,b,[a.i.visualElement],void 0)},uoa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={A:"div",U:["ytp-ce-element","ytp-ce-video"],K:{tabindex:"0","aria-label":b.Ji||"","aria-hidden":"true"},H:[{A:"div",F:"ytp-ce-element-shadow"},{A:"div",F:"ytp-ce-covering-image",K:L0(b)},{A:"div",F:"ytp-ce-covering-shadow-top"},{A:"a",F:"ytp-ce-covering-overlay",K:{href:M0(a,b.targetUrl),tabindex:"-1"},H:[{A:"div",U:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],K:{dir:g.rn(b.title||"")},T:b.title},{A:"div",F:"ytp-ce-video-duration",T:b.videoDuration}]}]};
c=new g.T(c);break;case "PLAYLIST":c={A:"div",U:["ytp-ce-element","ytp-ce-playlist"],K:{tabindex:"0","aria-label":b.Ji||"","aria-hidden":"true"},H:[{A:"div",F:"ytp-ce-element-shadow"},{A:"div",F:"ytp-ce-covering-image",K:L0(b)},{A:"div",F:"ytp-ce-covering-shadow-top"},{A:"a",F:"ytp-ce-covering-overlay",K:{href:M0(a,b.targetUrl),tabindex:"-1"},H:[{A:"div",U:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],K:{dir:g.rn(b.title||"")},T:b.title},{A:"div",F:"ytp-ce-playlist-count",H:[{A:"div",
F:"ytp-ce-playlist-icon"},{A:"div",F:"ytp-ce-playlist-count-text",T:b.playlistLength}]}]}]};c=new g.T(c);break;case "CHANNEL":c={A:"div",U:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],K:{tabindex:"0","aria-label":b.Ji||"","aria-hidden":"true"},H:[{A:"div",F:"ytp-ce-element-shadow"},{A:"div",F:"ytp-ce-expanding-overlay",H:[{A:"div",F:"ytp-ce-expanding-overlay-hider"},{A:"div",F:"ytp-ce-expanding-overlay-background"},{A:"div",F:"ytp-ce-expanding-overlay-content",
H:[{A:"div",F:"ytp-ce-expanding-overlay-body",H:[{A:"div",F:"ytp-ce-expanding-overlay-body-padding",H:[{A:"a",U:["ytp-ce-channel-title","ytp-ce-link"],K:{href:M0(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.rn(b.title||"")},T:b.title},b.subscribeButton?{A:"div",F:"ytp-ce-subscribe-container",H:[{A:"div",F:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{A:"div",F:"ytp-ce-channel-subscribers-text",T:b.subscribersText}:"",b.metadata?{A:"div",U:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
T:b.metadata}:""]}]}]}]},{A:"div",F:"ytp-ce-expanding-image",K:L0(b)}]};c=new g.T(c);var d=g.Cd(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.J(d,"ytp-ce-subscribe-button");if(a.player.L().g){var e=null;var f=b.Gb.itct}else e="endscreen",f=null;e=new g.kQ(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.D.push(e)}break;case "WEBSITE":c={A:"div",U:["ytp-ce-element","ytp-ce-website"],K:{tabindex:"0","aria-label":b.Ji||"","aria-hidden":"true"},H:[{A:"div",F:"ytp-ce-element-shadow"},{A:"div",F:"ytp-ce-expanding-overlay",H:[{A:"div",F:"ytp-ce-expanding-overlay-hider"},{A:"div",F:"ytp-ce-expanding-overlay-background"},{A:"div",F:"ytp-ce-expanding-overlay-content",H:[{A:"div",F:"ytp-ce-expanding-overlay-body",
H:[{A:"div",F:"ytp-ce-expanding-overlay-body-padding",H:[{A:"div",F:"ytp-ce-website-title",K:{dir:g.rn(b.title||"")},T:b.title},{A:"div",F:"ytp-ce-website-metadata",T:b.metadata},{A:"a",U:["ytp-ce-website-goto","ytp-ce-link"],K:{href:M0(a,b.targetUrl),target:"_blank",tabindex:"-1"},T:b.callToAction}]}]}]}]},{A:"div",F:"ytp-ce-expanding-image",K:L0(b)},{A:"div",F:"ytp-ce-expanding-icon",K:N0(b.iconUrl)}]};c=new g.T(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&b.additionalFeesText&&(c={A:"div",
F:"ytp-ce-merchandise-price-container",H:[{A:"div",F:"ytp-ce-merchandise-price",T:b.productPrice},{A:"div",F:"ytp-ce-merchandise-additional-fees",T:b.additionalFeesText}]}),c={A:"div",U:["ytp-ce-element","ytp-ce-merchandise"],K:{tabindex:"0","aria-label":b.Ji||"","aria-hidden":"true"},H:[{A:"div",F:"ytp-ce-element-shadow"},{A:"div",F:"ytp-ce-expanding-overlay",H:[{A:"div",F:"ytp-ce-expanding-overlay-hider"},{A:"div",F:"ytp-ce-expanding-overlay-background"},{A:"div",F:"ytp-ce-expanding-overlay-content",
H:[{A:"div",F:"ytp-ce-expanding-overlay-body",H:[{A:"div",F:"ytp-ce-expanding-overlay-body-padding",H:[{A:"div",F:"ytp-ce-merchandise-title",K:{dir:g.rn(b.title||"")},T:b.title},c,{A:"div",F:"ytp-ce-merchandise-metadata",T:b.metadata},{A:"div",F:"ytp-ce-merchandise-expanded-cta-container",H:[{A:"a",U:["ytp-ce-merchandise-goto","ytp-ce-link"],K:{href:M0(a,b.targetUrl),target:"_blank",tabindex:"-1"},T:b.callToAction},{A:"div",F:"ytp-ce-merchandise-cta-external"}]}]}]}]}]},{A:"div",F:"ytp-ce-expanding-image",
K:L0(b)},{A:"div",F:"ytp-ce-merchandise-invideo-cta-container",H:[{A:"div",F:"ytp-ce-merchandise-invideo-cta",T:b.callToAction}]}]},c=new g.T(c)}b.UC&&g.J(c.element,"ytp-ce-placeholder");return c},L0=function(a){if(a.Yt)var b=a.Yt.thumbnails;
return N0(b?b[b.length-1].url:null)},N0=function(a){return a?{style:"background-image: url("+a+")"}:{}},voa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ea("mouseenter",(0,g.x)(a.cq,a,b,c));b.ea("mouseleave",(0,g.x)(a.Rq,a,b,c));a.player.L().g||b.ea("click",(0,g.x)(function(l){g.J(l.element,"ytp-ce-element-hover")},a,b));
b.ea("click",(0,g.x)(a.Cx,a,c));b.ea("keypress",(0,g.x)(a.Cx,a,c));b.ea("focus",(0,g.x)(function(l,m){this.cq(l,m)},a,b,c));
b.ea("blur",(0,g.x)(function(l,m){this.Rq(l,m)},a,b,c));
b.ea("touchstart",(0,g.x)(a.cq,a,b,c));var f=g.Ed("ytp-ce-expanding-overlay-hider",b.element);f&&b.J(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.ln(b.element,"ytp-ce-element-hover");g.ln(b.element,"ytp-ce-force-expand")});
b.ea("keydown",(0,g.x)(function(l,m){this.I=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.x)(function(l,m,n){this.C+=n;0<this.C?(g.J(l.element,"ytp-ce-force-expand"),O0(this,m.id,!0)):(g.ln(l.element,"ytp-ce-force-expand"),g.ln(l.element,"ytp-ce-element-hover"),O0(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.ea("blur",g.Ra(function(){"none"!=m.style.display&&a.I&&m.focus()})),l.J(m,"focus",d),l.J(m,"blur",e))},a,b);
c(g.Ed("ytp-sb-subscribe",b.element));c(g.Ed("ytp-sb-unsubscribe",b.element));b.ea("focus",d);b.ea("blur",e)},M0=function(a,b){var c=a.player.L();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.uz(c)+b}else return"";return b},O0=function(a,b,c){a.l&&(c?a.w.show():a.w.hide());
for(var d in a.g)d!=b&&g.K(a.g[d].element,"ytp-ce-element-shadow-show",c)},P0=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||J0(a))c&&c();else{b=woa(a,b);var e=0,f=!1,k=new g.I(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Vp(b[a],d)}},Q0=function(a,b,c){P0(a,b.clickUrls,c);
(a=g.UA())&&b.QC&&g.NA(a,b.visualElement)},woa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(xoa(b[e],c));return d},xoa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},R0=function(a){return g.La(a)&&a.length?a[0]:a},S0=function(a){return g.Da(a)?a:""},T0=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},zoa=function(a){var b=yoa;
if(null==a)return null;if(g.Ma(a)){var c=[];(0,g.z)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},Aoa=function(a){this.externalId=a},U0=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.g=d},V0=function(a){if(!a)return null;
var b=g.Bc(S0(a.value));b=g.zc(b);if(!b)return null;var c=T0(a.target,Boa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new U0(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},W0=function(a){return a.value?a.value:null},X0=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},yoa=function(a){if(!a)return null;
var b=T0(a.type,Coa),c=T0(a.trigger,Doa),d=R0(a.url);d=V0(d?d:null);a=R0(a.subscribeData);var e=a?a:null;e?(a=S0(e.external_user_id),e=S0(e.subscription_token),a=a&&e?new Aoa(a):null):a=null;return b?new X0(b,c,d,a):null},Y0=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.g=d||[];this.data=e},Z0=function(a){return(a=Eoa(a,function(b){return"openUrl"==b.type&&null!=b.url}))?a.url:null},Eoa=function(a,b){return g.Ya(a.g,b,void 0)},$0=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Foa=function(a,b){this.merchant=a;
this.price=b},Goa=function(a){this.g=a},Hoa=function(a,b,c){b&&(c?a1(a,(0,g.fe)(b,g.Ra(function(d,e){return g.Ym(e,d)},c))):a1(a,b))},a1=function(a,b,c,d){var e=1,f=-1;
if(c){var k=!1;var l=function(){e--;e||k||(clearTimeout(f),k=!0,c())};
f=setTimeout(function(){k=!0;c()},1E3)}(0,g.z)(b||[],function(m){e++;
g.Vp(m,l)});
d&&(e++,0!=d&&a.g.sendVideoStatsEngageEvent(d,l))},Ioa=function(a,b,c,d,e,f,k){this.g=a;
this.l=b;this.Ya=c;this.videoData=d;this.logger=e;this.Z=f;this.i=k},b1=function(a,b){this.g=a;
this.l=b},Koa=function(a,b){var c=[];
(0,g.z)(b.choices,function(k){c.push(Joa(b,k))},a);
var d={A:"ul",K:{role:"radiogroup"},H:c},e={};b.oh&&(e["aria-label"]=g.WL("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{A:"div",F:"iv-card-content",H:[c1("h2",e,b.title),{A:"form",H:[{A:"fieldset",H:[d]}]}]}];b.oh&&(f.push("iv-card-unavailable"),d.push({A:"div",U:["iv-card-sign-in"],H:[{A:"h2",T:"Want to vote?"},{A:"a",U:["iv-card-sign-in-button","iv-button"],K:{href:W0(b.oh)},H:[{A:"span",U:["iv-button-content"],T:"Sign in"}]}]}));f=new g.T({A:"div",
U:f,H:d});d=f.element;d1(b,d);roa(a.g.g,d,g.Ra(a.o,b),a);(0,g.z)(g.Dd("iv-card-poll-choice-input",d),function(k){this.g.g.ea(k,"focus",g.Ra(this.i,!0));this.g.g.ea(k,"blur",g.Ra(this.i,!1))},a);
b.oh&&(d=g.Ed("iv-card-sign-in-button",d),a.l(d,b.oh,b.id,b.Gb,b.tc.click,5));return f},h1=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.NL?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.TC&&b.vt?{A:"span",U:d,K:e,T:b.vt}:"";c={A:"div",U:["iv-card",c],H:[{A:"a",F:"iv-click-target",K:{href:W0(b.url)},H:[e1(b.qh,d?{A:"div",F:"iv-card-image-text",H:[d,b.priceText]}:""),{A:"div",F:"iv-card-content",H:[{A:"h2",F:"iv-card-primary-link",T:b.title},f1(a,b)]}]}]};c=new g.T(c);g1(a,g.Dd("iv-click-target",c.element),b,b.url);return c},i1=function(a){return a.customMessage?
c1("div","iv-card-message",a.customMessage):""},e1=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{A:"div",F:"iv-card-image",K:{style:c},H:d}},f1=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.z)(b.metaInfo,function(d){c.push(c1("li","",d))},a);
return{A:"ul",F:"iv-card-meta-info",H:c}},Joa=function(a,b){return{A:"li",
F:$0(a,b.index),H:[{A:"label",H:[{A:"input",F:"iv-card-poll-choice-input",K:{type:"checkbox",role:"radio",name:a.id.replace(/[^a-z0-9-]/gi,"-")+b.index.toString(),value:b.index.toString(),"data-poll-choice-index":b.index.toString()}},{A:"span",F:"iv-card-poll-choice-text",H:[{A:"span",F:"iv-card-poll-choice-percent"},c1("span",void 0,b.desc)]}]},{A:"div",F:"iv-card-poll-result",H:[{A:"div",F:"iv-card-poll-result-bar"}]}]}},c1=function(a,b,c){b?g.Da(b)?b={"class":b}:g.La(b)&&(b={"class":b.join(" ")}):
b={};
b.dir=g.rn(c);return{A:a,K:b,T:c}},j1=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.ll&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.ll+");");c.dir=g.rn(a.customMessage);var d=[{A:"span",T:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({A:"span",F:"iv-card-link-icon"}));return{A:"div",U:b,K:c,H:d}},d1=function(a,b){var c=0;
(0,g.z)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Ed($0(a,e.index),b);e=e.count/c;null==a.fe&&(e=0);g.K(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.fe==d);f.getElementsByTagName("input")[0].checked=a.fe==d;var k=Math.floor(100*e).toFixed(0),l=g.Ed("iv-card-poll-choice-percent",f);g.$d(l,g.WL("$PERCENT%",{PERCENT:k}));f=g.Ed("iv-card-poll-result-bar",f);g.Zf(f,"transform","scaleX("+e.toFixed(2)+")")}g.K(b,"iv-card-poll-voted",null!=a.fe);g.K(b,"iv-card-poll-expanded",
null!=a.fe&&1<a.choices.length)},g1=function(a,b,c,d){d&&(0,g.z)(b,function(e){this.l(e,d,c.id,c.Gb,c.tc.click,5)},a)},k1=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},Loa=function(a,b){return b?b:k1(a)?"current":"new"},l1=function(a,b){g.E.call(this);
this.g=a;this.context=b;this.Tr=!1},Moa=function(a,b,c,d,e){var f=W0(b);
if(f){var k=Loa(f,b.target),l=(0,g.x)(function(){b.g&&this.context.Z.pauseVideo();var m=this.context.videoData.ac||!1,n=g.gp(f||"");m&&n&&(n.v||n.list)?g.HS(this.context.Z.app,n.v,c,n.list,!1,void 0):g.bM(f||"","current"==k?"_top":void 0,c)},a);
"new"==k&&(l(),l=null);a1(a.context.logger,d,l,e);k1(f)||(a=g.UA(),d=c.itct,a&&d&&g.NA(a,g.yA(d)))}},m1=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},n1=function(a,b,c){return{lv:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
mz:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
Cn:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},q1=function(a,b,c){l1.call(this,b,c);
var d=this;this.l=a;this.W=this.xa=this.w=this.va=!1;this.X=null;this.aa=new g.I(g.Ia,c.Ya.fd?4E3:3E3);g.H(this,this.aa);this.ka=new g.I(g.Ia);g.H(this,this.ka);this.D=new b1(c,(0,g.x)(this.wi,this),(0,g.x)(this.lm,this));this.P=new g.T({A:"div",F:"iv-drawer",K:{id:"iv-drawer"},H:[{A:"div",F:"iv-drawer-header",K:{"aria-role":"heading"},H:[{A:"span",F:"iv-drawer-header-text"},{A:"button",U:["iv-drawer-close-button","ytp-button"],K:{"aria-label":"Hide cards",tabindex:"0"}}]},{A:"div",F:"iv-drawer-content"}]});
g.H(this,this.P);this.B=this.P.element;this.ma=new g.pL(this.P,330);g.H(this,this.ma);this.ua=g.Ed("iv-drawer-header-text",this.B);this.u=g.Ed("iv-drawer-content",this.B);this.o=[];this.la=this.M=this.C=this.ca=this.i=null;this.S=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.xa&&o1(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.xa=d.w)&&p1(d)});
this.R=this.G=this.Y=null;this.I=0},Noa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){o1(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){p1(a)});
var c=b.data.headerText;g.$d(a.ua,c);a.M&&a.M.setAttribute("title",c);a.Y=g.yA(b.data.trackingParams);a.R=g.yA(b.data.closeTrackingParams);a.G=g.yA(b.data.iconTrackingParams)},Ooa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"simple",teaserText:g.JB(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Gb:r1(a,c,b),sponsored:!1,tc:n1(d,e,d.command),Fd:d.trackingParams?g.yA(d.trackingParams):null,Cd:e.trackingParams?
g.yA(e.trackingParams):null,Rc:f&&f.trackingParams?g.yA(f.trackingParams):null,imageUrl:d.image.thumbnails[0].url,displayDomain:d.displayDomain?g.JB(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,ll:null,title:d.title?g.JB(d.title):"",customMessage:d.callToAction?g.JB(d.callToAction):"",url:d.command.urlEndpoint.url?V0({pause_on_navigation:!a.context.videoData.na,target:"new",value:d.command.urlEndpoint.url}):null};s1(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"collaborator",teaserText:g.JB(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Gb:r1(a,c,b),sponsored:!1,tc:n1(d,e,d.endpoint),Fd:d.trackingParams?g.yA(d.trackingParams):null,Cd:e.trackingParams?g.yA(e.trackingParams):null,Rc:f&&f.trackingParams?g.yA(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.JB(d.customText):null,qy:d.channelAvatar.thumbnails[0].url,title:d.channelName?g.JB(d.channelName):"",metaInfo:[d.subscriberCountText?g.JB(d.subscriberCountText):""],url:V0({pause_on_navigation:!a.context.videoData.na,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};s1(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"playlist",teaserText:g.JB(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Gb:r1(a,c,b),sponsored:!1,tc:n1(d,e,d.action),Fd:d.trackingParams?g.yA(d.trackingParams):null,Cd:e.trackingParams?g.yA(e.trackingParams):null,Rc:f&&f.trackingParams?g.yA(f.trackingParams):
null,qh:d.playlistThumbnail.thumbnails[0].url,customMessage:d.customMessage?g.JB(d.customMessage):null,playlistVideoCount:g.JB(d.playlistVideoCount),title:d.playlistTitle?g.JB(d.playlistTitle):"",metaInfo:[d.channelName?g.JB(d.channelName):"",d.videoCountText?g.JB(d.videoCountText):""],url:V0({pause_on_navigation:!a.context.videoData.na,target:"new",value:m1(d.action)})};s1(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"video",teaserText:g.JB(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Gb:r1(a,c,b),sponsored:!1,tc:n1(d,e,d.action),Fd:d.trackingParams?g.yA(d.trackingParams):null,Cd:e.trackingParams?g.yA(e.trackingParams):null,Rc:f&&f.trackingParams?g.yA(f.trackingParams):null,qh:d.videoThumbnail.thumbnails[0].url,
videoDuration:d.lengthString?g.JB(d.lengthString):null,customMessage:d.customMessage?g.JB(d.customMessage):null,title:d.videoTitle?g.JB(d.videoTitle):"",metaInfo:[d.channelName?g.JB(d.channelName):"",d.viewCountText?g.JB(d.viewCountText):""],isLiveNow:!!d.badge,url:V0({pause_on_navigation:!a.context.videoData.na,target:"new",value:m1(d.action)})};s1(a,c)}a.I++},r1=function(a,b,c){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:c.trackingParams}},u1=function(a,b){var c=Poa(a,b);
c&&(c==a.i&&(a.i=null),a.l.removeCueRange(c.card.id),g.Vd(c.Bo),g.eb(a.o,c),a.ol(),t1(a))},o1=function(a,b,c){if(!a.w){a.ma.show();
a.ca=new g.I(function(){g.J(a.context.Z.getRootNode(),"ytp-iv-drawer-open")},0);
a.ca.start();a.X=g.Zq(a.u,"mousewheel",(0,g.x)(a.VD,a));a.w=!0;var d=g.UA();d&&a.Y&&a.R&&s0(d,[a.Y,a.R]);var e={TRIGGER_TYPE:b};(0,g.z)(a.o,function(f){f.Qv||(f.Qv=!0,Hoa(a.context.logger,f.card.tc.lv,e));d&&s0(d,[f.card.Fd])});
r0(a.l);c&&(a.C=new g.I(function(){a.da=a.M;a.la.focus()},330),a.C.start())}},p1=function(a){a.w&&(a.ma.hide(),g.$q(a.X),a.X=null,g.ln(a.context.Z.getRootNode(),"ytp-iv-drawer-open"),a.w=!1,r0(a.l),a.C&&a.C.stop(),a.C=new g.I(function(){a.da&&(a.da.focus(),a.da=null)},330),a.C.start())},Qoa=function(a){var b=g.Ed("iv-drawer-close-button",a.B);
a.context.g.ea(b,"click",a.hB,a);a.context.g.ea(a.u,"touchend",function(){a.aa.start()});
a.context.g.ea(a.u,"scroll",a.uB,a);a.context.i.subscribe("onHideControls",function(){a.W=!0});
a.context.i.subscribe("onShowControls",function(){a.W=!1});
a.context.i.subscribe("onVideoAreaChange",function(){a.W=g.jn(a.l.getRootNode(),"ytp-autohide")});
a.S.push(g.Jo("iv-button-shown",a.dD,a));a.S.push(g.Jo("iv-button-hidden",a.cD,a));a.S.push(g.Jo("iv-teaser-shown",a.gD,a));a.S.push(g.Jo("iv-teaser-hidden",a.fD,a));a.S.push(g.Jo("iv-teaser-clicked",a.eD,a))},s1=function(a,b){a.va||(g.kn(a.g,["html5-stop-propagation",
"iv-drawer-manager"]),g.DK(a.l,a.B,5),Qoa(a),a.M=g.Ed("ytp-cards-button",a.l.getRootNode()),a.la=g.Ed("iv-drawer-close-button",a.B),a.va=!0);u1(a,b.id);var c=Roa(a,b);if(c){var d={card:b,Bo:c.element,Qv:!1},e=Soa(a,d);g.lb(a.o,e,0,d);c.g(a.u,e);a.ol();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Ra(a.iL,d)):(c=1E3*a.context.Z.getCurrentTime(),5E3>c&&c>b.startMs&&a.Wy(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Ra(a.Wy,d)),t1(a))}},Roa=function(a,b){switch(b.type){case "simple":var c=
a.D;
var d=b.displayDomain?{A:"div",F:"iv-card-image-text",T:b.displayDomain}:"";var e=j1(b);d={A:"div",U:["iv-card"],H:[{A:"a",F:"iv-click-target",K:{href:W0(b.url)},H:[e1(b.imageUrl,d),{A:"div",F:"iv-card-content",H:[c1("h2",void 0,b.title),e]}]}]};d=new g.T(d);g1(c,g.Dd("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.D,d={A:"div",U:["iv-card","iv-card-channel"],H:[{A:"a",U:["iv-click-target"],K:{href:W0(b.url),"data-ytid":b.channelId},H:[e1(b.qy),{A:"div",F:"iv-card-content",
H:[i1(b),{A:"h2",F:"iv-card-primary-link",T:b.title},f1(c,b)]}]}]},d=new g.T(d),g1(c,g.Dd("iv-click-target",d.element),b,b.url),d;case "episode":return h1(a.D,b,"iv-card-episode");case "movie":return h1(a.D,b,"iv-card-movie");case "playlist":return c=a.D,d={A:"div",U:["iv-card","iv-card-playlist"],H:[{A:"a",F:"iv-click-target",K:{href:W0(b.url)},H:[e1(b.qh,{A:"div",F:"iv-card-image-overlay",H:[{A:"span",F:"iv-card-playlist-video-count",T:b.playlistVideoCount}]}),{A:"div",F:"iv-card-content",H:[i1(b),
c1("h2","iv-card-primary-link",b.title),f1(c,b)]}]}]},d=new g.T(d),g1(c,g.Dd("iv-click-target",d.element),b,b.url),d;case "poll":return Koa(a.D,b);case "productListing":c=a.D;var f=!g.bb(b.offers);d=["iv-card"];e="";var k=j1(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],k=[],f.price&&k.push({A:"div",F:"iv-card-offer-price",T:f.price}),f.merchant&&k.push({A:"div",F:"iv-card-offer-merchant",T:f.merchant}),k={A:"div",H:k});d={A:"div",U:d,K:{tabindex:"0"},H:[{A:"a",U:["iv-card-image",
"iv-click-target"],K:{style:"background-image: url("+b.imageUrl+");",href:W0(b.url),"aria-hidden":"true",tabindex:"-1"}},{A:"div",F:"iv-card-content",H:[b.sponsored?{A:"div",F:"iv-card-sponsored",H:["Sponsored",{A:"div",F:"iv-ad-info-container",H:[{A:"div",F:"iv-ad-info",T:"{{adInfo}}"},{A:"div",F:"iv-ad-info-icon-container",H:[{A:"div",F:"iv-ad-info-icon"},{A:"div",F:"iv-ad-info-callout"}]}]}]}:"",{A:"a",F:"iv-click-target",K:{href:W0(b.url)},H:[c1("h2",e,b.title),k]}]}]};d=new g.T(d);e=g.Qd("span");
g.$d(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.ib(e,"adInfo");g1(c,g.Dd("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.D,d=b.isLiveNow?{A:"span",U:["yt-badge","yt-badge-live"],T:"LIVE NOW"}:"",d={A:"div",U:["iv-card","iv-card-video"],H:[{A:"a",F:"iv-click-target",K:{href:W0(b.url)},H:[e1(b.qh,b.videoDuration?{A:"span",F:"iv-card-video-duration",T:b.videoDuration}:""),{A:"div",F:"iv-card-content",
H:[i1(b),c1("h2","iv-card-primary-link",b.title),f1(c,b),d]}]}]},d=new g.T(d),g1(c,g.Dd("iv-click-target",d.element),b,b.url),d}return null},Soa=function(a,b){if(0==a.o.length)return 0;
var c=g.Za(a.o,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},Toa=function(a){return a.i?"productListing"==a.i.card.type:(0,g.Yg)(a.o,function(b){return"productListing"==b.card.type})},t1=function(a){g.K(a.l.getRootNode(),"ytp-cards-shopping-active",Toa(a))},v1=function(a,b){if(a.P.Da()){var c=new z0([0,
a.u.scrollTop],[0,b.Bo.offsetTop],600,poa);a.context.l.ea(c,"animate",function(d){a.u.scrollTop=d.y});
a.context.l.ea(c,"finish",function(d){a.u.scrollTop=d.y});
c.play()}else g.Au(a.P,!0),a.u.scrollTop=b.Bo.offsetTop,g.Au(a.P,!1)},w1=function(a){return a.i&&a.i.card?a.i.card:a.o[0]&&a.o[0].card?a.o[0].card:null},Poa=function(a,b){return g.Ya(a.o,function(c){return c.card.id==b})},x1=function(a,b,c){l1.call(this,a,b);
this.annotation=c;this.isActive=!1},Uoa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},y1=function(a,b,c){x1.call(this,a,b,c);
this.l=null;this.C=!1;this.o=null;this.u=!1;this.i=this.B=this.w=null},z1=function(a,b,c){x1.call(this,a,b,c);
this.G=this.w=this.I=!1;this.C=5E3;this.u=null;this.D=g.Pd("DIV","iv-promo-contents");this.l=this.o=this.i=null;this.B=new g.I(function(){this.i.setAttribute("aria-hidden",!0);g.tg(this.o,!1);g.tg(this.l,!0)},700,this);
g.H(this,this.B)},Voa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.C=b.collapse_delay_ms||a.C;var d=["iv-promo","iv-promo-inactive"];a.g.setAttribute("aria-hidden",!0);a.g.setAttribute("aria-label","Promotion");a.g.tabIndex=0;var e=Z0(a.annotation),f=b.image_url;if(f){var k=g.Pd("DIV",["iv-promo-img","iv-click-target"]);f=g.Pd("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.Pd("SPAN","iv-promo-video-duration",b.video_duration),
k.appendChild(f)):b.playlist_length&&(f=g.Pd("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.wi(k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=g.Pd("A","iv-promo-txt"),g.Tc(f,W0(e)),a.i=f):a.i=g.Pd("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Pd("P",null,g.Pd("STRONG",null,b.text_line_1));var m=g.Pd("P",null,g.Pd("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");g.P(a.context.Ya.experiments,
"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Pd("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Pd("BUTTON",["iv-button","iv-promo-button"],g.Pd("SPAN","iv-button-content",f));var q=g.Pd("DIV","iv-promo-button-container");q.appendChild(f);e&&a.wi(a.g,e,a.annotation.id,b.session_data,void 0,c)}g.J(a.i,"iv-click-target");e&&a.wi(a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=g.Pd("P",null,g.Pd("SPAN",null,b.text_line_1)),
m=g.Pd("P",null,g.Pd("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Pd("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.J(a.i,"iv-click-target"),e&&a.wi(a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.D.appendChild(a.i);q&&a.D.appendChild(q);c=g.Pd("DIV","iv-promo-actions");a.l=g.Pd("BUTTON",["iv-promo-expand","ytp-button"]);a.l.title="Expand";a.context.g.ea(a.l,"click",g.Ra(a.pp,5E3),a);c.appendChild(a.l);g.tg(a.l,!1);
a.context.g.ea(a.g,"mouseover",a.kC,a);a.context.g.ea(a.g,"mouseout",a.jC,a);a.context.g.ea(a.g,"touchend",g.Ra(a.pp,5E3),a);a.o=g.Pd("BUTTON",["iv-promo-close","ytp-button"]);a.o.title="Close";a.context.g.ea(a.o,"click","cta"==a.annotation.style&&b.text_line_3?a.dC:a.cC,a);c.appendChild(a.o);g.kn(a.g,d);k&&(a.g.appendChild(k),n&&k.appendChild(n));a.g.appendChild(a.D);a.g.appendChild(c)},A1=function(a){a.w||a.G||a.u||(g.J(a.g,"iv-promo-collapsed"),a.w=!0,a.B.start())},B1=function(a){a.B.stop();
a.w&&(g.mn(a.g,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.w=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.tg(a.l,!1),g.tg(a.o,!0))},D1=function(a,b){a.u||(a.u=g.hl(function(){C1(this);
A1(this)},b,a))},C1=function(a){a.u&&(g.u.clearTimeout(a.u),a.u=null)},E1=function(a){g.aP.call(this,a);
this.G=!1;this.D=0;this.B={};this.P=new Goa(a);this.u=new g.Qs(this);g.H(this,this.u);this.w=this.l=null;this.u.J(this.player,"onVideoAreaChange",(0,g.x)(this.N,this,"onVideoAreaChange"));this.u.J(this.player,"onHideControls",(0,g.x)(this.N,this,"onHideControls"));this.u.J(this.player,"onShowControls",(0,g.x)(this.N,this,"onShowControls"));this.u.J(this.player,"resize",(0,g.x)(this.N,this,"resize"));this.u.J(this.player,"presentingplayerstatechange",(0,g.x)(this.N,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.UI,this);this.subscribe("resize",this.an,this);this.player.L().C.subscribe("vast_info_card_add",this.dy,this);this.M=new g.Qs(this);g.H(this,this.M);this.R=g.Pd("DIV","video-custom-annotations");this.i=new g.T({A:"div",U:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.i);g.DK(this.player,this.i.element,4);this.i.hide();this.o=new g.T({A:"div",U:["ytp-iv-video-content"]});g.H(this,this.o);g.Sd(this.o.element,g.Pd("DIV","video-annotations",
this.R));this.C=this.g=null;this.I=[];Woa(this)&&this.load();var b=g.Qd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Bi(this,function(){g.Vd(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},F1=function(){var a=g.Pd("DIV",["annotation",
"annotation-type-custom"]);g.tg(a,!1);return a},G1=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},Woa=function(a){var b=a.player.L();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.Pz||null!==b.C.get(a.videoId)},H1=function(a,b,c){a.G=!0;
a.w=g.Ap(b,c)},I1=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Oa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(I1(a,e))}return c},J1=function(a,b,c){return!(a.loaded&&a.D==b&&a.player.getVideoData().videoId==
c)},Xoa=function(a){var b=a.player.getVideoData();
if(b.Ed){var c=a.player.L().C.get(b.videoId);if(c){var d={format:"XML",od:{},method:"POST",withCredentials:!0};d.Xc=(0,g.x)(function(e,f,k){J1(this,e,f)||(e=g.up(k)&&k.responseXML?k.responseXML:null)&&K1(this,e)},a,a.D,b.videoId);
g.Xo()&&(d.Xc=L1(a,d.Xc));d.sb={ic_only:"1"};M1(d,c);a.G=!0;g.Ap(b.Ed,d)}}},M1=function(a,b){a.method="POST";
a.sb=a.sb||{};b.sl&&(a.sb.ic_coll=b.sl);b.tl&&(a.sb.ic_xml=b.tl);b.Jr&&(a.sb.ic_track=b.Jr)},O1=function(a){var b=new g.T({A:"div"});
g.tg(b.element,!1);var c=new q1(a.player,b.element,N1(a));g.H(c,b);b.g(a.i.element);c.mk();return c},N1=function(a){if(!a.C){var b=new E0(a);
g.H(a,b);var c=new g.sZ(a);g.H(a,c);a.C=new Ioa(b,c,a.player.L(),a.player.getVideoData(),a.P,a.player,a.Tb)}return a.C},K1=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.UA();if(e){var f=g.TA();f&&g.LA(e,f,[g.yA(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var k=I1(a,d[e]);f=null;try{if(k){var l=k.id,m=/.+/;var n=g.Da(l)&&null!=m&&null!=l&&l.match(m)?l:"";var q=T0(k.type,Yoa),t=T0(k.style,Zoa),v=S0(k.data),y=0!=v.length?JSON.parse(v):{},B=zoa(k.action);f=n&&q?new Y0(n,q,t,B,y):null}else f=null}catch(M){}if(f){a:{switch(f.type){case "branding":case "promotion":k=!0;break a}k=!1}if(k){k=
a;m=f;var C=F1(),G=null;switch(m.type){case "branding":if(k.player.L().dc)break;k.i.element.appendChild(C);G=new y1(C,N1(k),m);break;case "promotion":g.DK(k.player,C,4),G=new z1(C,N1(k),m)}G&&G.mk();if(k=G)g.H(a,k),a.B[f.id]=k}else if("card"==f.type||"drawer"==f.type){a.g||(a.g=O1(a),g.H(a,a.g));if("card"==f.type){if(c=a.g,G=f&&f.data&&f.data.card_type)switch(k=f.data.tracking||{},k={lv:k.impression,click:k.click,close:k.close,mz:k.teaser_impression,Cn:k.teaser_click},m=f.data.tracking_params||{},
C=null,G){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Gb:f.data.session_data||{},sponsored:f.data.sponsored||!1,tc:k,Fd:m.card?g.yA(m.card):null,Cd:m.teaser?g.yA(m.teaser):null,Rc:m.icon?g.yA(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,qy:f.data.image_url,title:f.data.title,
metaInfo:f.data.meta_info,url:V0({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};s1(c,f);break;case "episode":case "movie":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Gb:f.data.session_data||{},sponsored:f.data.sponsored||!1,tc:k,Fd:m.card?g.yA(m.card):null,Cd:m.teaser?g.yA(m.teaser):null,Rc:m.icon?g.yA(m.icon):
null,qh:f.data.image_url,vt:f.data.badge_symbol||"",priceText:f.data.price_text||"",title:f.data.title,metaInfo:f.data.meta_info,TC:!!f.data.is_paygated,NL:!!f.data.user_has_entitlement,url:V0({target:f.data.target||"new",value:f.data.url})};s1(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Gb:f.data.session_data||{},sponsored:f.data.sponsored||
!1,tc:k,Fd:m.card?g.yA(m.card):null,Cd:m.teaser?g.yA(m.teaser):null,Rc:m.icon?g.yA(m.icon):null,qh:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:V0({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};s1(c,f);break;case "poll":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,
startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Gb:f.data.session_data||{},sponsored:f.data.sponsored||!1,tc:k,Fd:m.card?g.yA(m.card):null,Cd:m.teaser?g.yA(m.teaser):null,Rc:m.icon?g.yA(m.icon):null,title:f.data.title,choices:f.data.choices,fe:f.data.hasOwnProperty("old_vote")?f.data.old_vote:null,oh:f.data.signin_url?V0({target:"current",value:f.data.signin_url}):null,XL:f.data.hasOwnProperty("xsrf_token")?f.data.xsrf_token:null};s1(c,f);break;case "productListing":f.data.signin_url&&(C=V0({target:"current",
value:f.data.signin_url}));G=[];for(var L=f.data.offers||[],F=0;F<L.length;F++)G.push(new Foa(g.ad(L[F].merchant),g.ad(L[F].price)));f={TP:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Gb:f.data.session_data||{},sponsored:f.data.sponsored||!1,tc:k,Fd:m.card?g.yA(m.card):null,Cd:m.teaser?g.yA(m.teaser):null,Rc:m.icon?g.yA(m.icon):null,imageUrl:f.data.image_url,
displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,ll:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:V0({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),oh:C,cQ:f.data.signin_title?f.data.signin_title:null,bQ:f.data.signin_message?f.data.signin_message:null,offers:G};s1(c,f);break;case "simple":f={id:f.id,timestamp:f.data.timestamp||
0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Gb:f.data.session_data||{},sponsored:f.data.sponsored||!1,tc:k,Fd:m.card?g.yA(m.card):null,Cd:m.teaser?g.yA(m.teaser):null,Rc:m.icon?g.yA(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,ll:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,
customMessage:f.data.custom_message?f.data.custom_message:null,url:V0({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};s1(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Gb:f.data.session_data||{},sponsored:f.data.sponsored||!1,tc:k,Fd:m.card?g.yA(m.card):null,Cd:m.teaser?g.yA(m.teaser):
null,Rc:m.icon?g.yA(m.icon):null,qh:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:V0({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},s1(c,f)}}else Noa(a.g,f);c=!0}}}c&&(r0(a.player),a.an())},$oa=function(a,b){var c=!1;
a.g||(a.g=O1(a),g.H(a,a.g));for(var d=g.p(b.cards||[]),e=d.next();!e.done;e=d.next())Ooa(a.g,e.value.cardRenderer),c=!0;c&&(c=a.g,d=b.headerText?g.JB(b.headerText):"",g.$d(c.ua,d),c.M&&c.M.setAttribute("title",d),c.Y=b.trackingParams?g.yA(b.trackingParams):null,c.R=b.closeButton.infoCardIconRenderer.trackingParams?g.yA(b.closeButton.infoCardIconRenderer.trackingParams):null,c.G=b.icon.infoCardIconRenderer.trackingParams?g.yA(b.icon.infoCardIconRenderer.trackingParams):null,r0(a.player),a.an())},apa=
function(a,b,c,d){if(!a.player.L().dc){var e=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&e.push(new X0("openUrl","click",new U0("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var f=b.watermark.thumbnails[0];b=new Y0("branding","branding","branding",e,{channel_id:"",channel_name:b.channelName,end_ms:b.endTimeMs,image_height:f.height,image_type:1,image_url:f.url,image_width:f.width,is_mobile:!1,session_data:{annotation_id:"branding",ei:d,feature:"iv",itct:b.trackingParams,
src_vid:c},standalone_subscribe_button_data:null,start_ms:b.startTimeMs});c=F1();a.i.element.appendChild(c);b=new y1(c,N1(a),b);b.mk();g.H(b,b);a.B.branding=b}},L1=function(a,b){return(0,g.x)(function(){if(!this.fa()){var c=Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Ra.apply(window,c);this.I.push(g.Vo(b))}},a)},u0={},v0=null;g.Ta(z0,g.nn);g.h=z0.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.g)this.progress=0,this.coords=this.l;else if(1==this.g)return!1;w0(this);this.startTime=a=(0,g.A)();-1==this.g&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.B=this.startTime;this.progress||this.u();this.Vd("play");-1==this.g&&this.Vd("resume");this.g=1;var b=g.Qa(this);b in u0||(u0[b]=this);x0();y0(this,a);return!0};
g.h.stop=function(a){w0(this);this.g=0;a&&(this.progress=1);A0(this,this.progress);this.Vd("stop");this.o()};
g.h.pause=function(){1==this.g&&(w0(this),this.g=-1,this.Vd("pause"))};
g.h.V=function(){0==this.g||this.stop(!1);this.Vd("destroy");z0.xb.V.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Mq=function(){this.Vd("animate")};
g.h.Vd=function(a){this.dispatchEvent(new B0(a,this))};
g.Ta(B0,g.Zj);g.Ta(C0,z0);C0.prototype.w=g.Ia;C0.prototype.Mq=function(){this.w();C0.xb.Mq.call(this)};
C0.prototype.o=function(){this.w();C0.xb.o.call(this)};
C0.prototype.u=function(){this.w();C0.xb.u.call(this)};
g.Ta(D0,C0);D0.prototype.w=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.r(E0,g.E);E0.prototype.ea=function(a,b,c,d){c=(0,g.x)(c,d||this.i);a=g.Zq(a,b,c);this.g.push(a);return a};
E0.prototype.Pp=function(a,b,c,d){c=(0,g.x)(c,d||this.i);a=g.ir(a,b,c);this.g.push(a);return a};
E0.prototype.Sa=function(a){g.$q(a);g.eb(this.g,a)};
E0.prototype.V=function(){g.$q(this.g);this.g.length=0;g.E.prototype.V.call(this)};g.r(H0,g.aP);g.h=H0.prototype;g.h.load=function(){g.aP.prototype.load.call(this);if(!J0(this)){var a=g.yC(this.player.getVideoData());if(a)a=G0(a,I0(this)),K0(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.o&&this.o.abort();a={method:"POST",Xc:(0,g.x)(this.FH,this,a),od:{v:a},withCredentials:!0};this.G&&(a.od.ptype="embedded");var c=this.player.getVideoData().du;c&&(a.sb={ad_tracking:c});if(b=g.xC(b))if(b=g.Bc(b),b=g.zc(b))this.o=g.Ap(b,a)}}};
g.h.unload=function(){K0(this,null);this.o&&(this.o.abort(),this.o=null);g.aP.prototype.unload.call(this)};
g.h.xc=function(a,b){if(!J0(this))return null;if("loadCustomEndscreenRenderer"==a){var c=G0(b,"new");K0(this,c);return!0}return null};
g.h.getOptions=function(){return J0(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.FH=function(a,b){var c=this.o=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=G0(c,I0(this)))}K0(this,c)};
g.h.Ma=function(){if(this.i&&this.i.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<P1.length;f++){var k=Math.abs(b.width-P1[f]);if(-1==e||d>=k)e=f,d=k}d=Q1[e];this.l&&g.Zf(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.i.elements.length;++b)if(f=this.i.elements[b].id,e=this.g[f],k=this.B[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.rg(e.element,Math.round(k.width*a.width),f);g.gg(e.element,m,n);g.mn(e.element,bpa);m=k.left+k.width/2;k=k.top+l/2;g.J(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.mn(e.element,Q1);g.J(e.element,d);(e=g.Cd(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Zf(e,"height",f+"px")}}}}};
g.h.AD=function(a){if(this.i)if("ytp-ce-in-endscreen"==a.getId())P0(this,this.i.impressionUrls),(a=g.UA())&&this.i.visualElement&&g.MA(a,this.i.visualElement);else{a=a.getId().substring(15);var b=this.g[a],c=this.B[a];g.J(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.J(b,"ytp-ce-shown");P0(this,c.impressionUrls);(b=g.UA())&&g.MA(b,c.visualElement);this.player.L().vb&&this.player.ha("endscreenelementshown",a)}};
g.h.BD=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.g[a];g.ln(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.ln(b,"ytp-ce-shown");this.player.L().vb&&this.player.ha("endscreenelementhidden",a)}};
g.h.wK=function(a){var b=this;a.target===window&&(new g.I(function(){for(var c in b.g)g.mn(b.g[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.Cx=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.jn(c,"ytp-ce-element");){g.jn(c,"subscribe-label")&&Q0(this,a);if(g.jn(c,"ytp-ce-channel-subscribe"))return;c=g.Yd(c)}if(!c||g.jn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.g[a.id])this.Rq(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.xL?(Q0(this,a),this.Vy(),this.player.pauseVideo(),c=g.Bc(M0(this,a.targetUrl)),c=g.zc(c),g.bM(c,void 0,a.Gb)):(c=this.player.getVideoData().ac,
c=(0,g.x)(this.pL,this,c,M0(this,a.targetUrl),a.Gb),c=(0,g.x)(this.Vy,this,c),Q0(this,a,c))}}};
g.h.pL=function(a,b,c){var d=g.gp(b);a&&d&&(d.v||d.list)?g.HS(this.player.app,d.v,c,d.list,!1,void 0):g.aM(b,c)};
g.h.cq=function(a,b){g.jn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.J(a.element,"ytp-ce-element-hover"):this.player.L().g?(new g.I(function(){g.J(a.element,"ytp-ce-element-hover")},200)).start():g.J(a.element,"ytp-ce-element-hover"),P0(this,b.HC),O0(this,b.id,!0))};
g.h.Rq=function(a,b){g.ln(a.element,"ytp-ce-element-hover");g.ln(a.element,"ytp-ce-force-expand");O0(this,b.id,!1)};
g.h.Vy=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var P1=[346,426,470,506,570,640,853,1280,1920],Q1="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),bpa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var Boa={eN:"current",xO:"new"};var Coa={CLOSE:"close",AO:"openUrl",JA:"subscribe"},Doa={XM:"click",CLOSE:"close",PN:"hidden",XO:"rollOut",YO:"rollOver",bP:"shown"};var Zoa={zM:"anchored",fA:"branding",CHANNEL:"channel",dN:"cta",RN:"highlightText",gO:"label",PLAYLIST:"playlist",KO:"popup",fP:"speech",JA:"subscribe",pP:"title",VIDEO:"video",CP:"website"},Yoa={fA:"branding",OM:"card",kN:"drawer",QN:"highlight",nO:"marker",PO:"promotion",TEXT:"text",EP:"widget"};b1.prototype.i=function(a,b){var c=g.ee(b.target,"label");c&&g.K(c,"iv-card-poll-choice-focused",a)};
b1.prototype.o=function(a,b){var c=g.ee(b.target,null,"iv-card-poll",void 0);if(c)if(a.oh)g.Ed("iv-card-sign-in-button",c).click();else{var d=parseInt(noa(b.target),10);if(null==a.fe)a.choices[d].count++,a.fe=d;else if(a.fe!=d){var e=a.choices[a.fe];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.fe=d}else e=a.choices[a.fe],e.count=Math.max(e.count-1,0),a.fe=null;d1(a,c);g.Ep(this.g.videoData.Ed,{od:{action_poll_vote:1},sb:{poll_id:a.id,index:d,session_token:a.XL}});a1(this.g.logger,a.tc.click,
void 0,5);(c=g.UA())&&a.Fd&&g.NA(c,a.Fd)}};g.r(l1,g.E);g.h=l1.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.xD(a,b,{id:c});g.H(this,a);a.namespace="annotations_module";d&&q0(a).subscribe("onEnter",d,this);e&&q0(a).subscribe("onExit",e,this);g.zK(this.context.Z,[a])};
g.h.mk=function(){this.context.i.subscribe("resize",this.ol,this)};
g.h.wi=function(a,b,c,d,e,f){this.context.g.ea(a,"click",g.Ra(this.lm,b,c,d,e||[],f||0),this);this.context.g.ea(a,"touchstart",g.Ra(function(){this.Tr=!1}),this);
this.context.g.ea(a,"touchmove",g.Ra(function(){this.Tr=!0}),this)};
g.h.lm=function(a,b,c,d,e,f){if(this.Tr)return!1;f&&(f.stopPropagation(),f.preventDefault());Moa(this,a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.Vd(this.g)};
g.h.ol=function(){};g.r(q1,l1);g.h=q1.prototype;g.h.isAvailable=function(){var a;if(a=!!this.o.length)(a=this.l.getRootNode())?(a=g.sg(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.ol=function(){var a=this.isAvailable();g.tg(this.g,a);g.K(this.context.Z.getRootNode(),"ytp-iv-drawer-enabled",a);r0(this.l)};
g.h.destroy=function(){var a=g.rK(g.gK(this.l));a&&a.bq(!1,void 0);this.l.getRootNode().removeChild(this.B);g.Ko(this.S);g.$q(this.X);this.ca&&this.ca.dispose();this.C&&this.C.dispose();l1.prototype.destroy.call(this)};
g.h.VD=function(a){this.aa.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.u.scrollTop+=a};
g.h.Wy=function(a){if(!g.jn(this.l.getRootNode(),"ytp-cards-teaser-shown")){if(this.i!=a){var b=g.UA(),c=this.i?this.i.card.Rc:this.G;b&&c&&t0(b,[c]);this.i=a;t1(this)}"none"!=this.g.style.display&&(2==this.context.Z.getPresentingPlayerType()?b=1==(isNaN(void 0)?this.context.Z.getAdState():void 0):(b=isNaN(void 0)?this.context.Z.getPlayerState():void 0,b=1==b||0==b&&0===this.context.Z.getCurrentTime()),b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},
(c=g.rK(g.gK(this.l)))&&c.bq(!0,b)));this.ka.isActive()||((!this.w||!this.aa.isActive()&&this.W)&&v1(this,a),this.ka.start(910+a.card.teaserDurationMs))}};
g.h.iL=function(a){this.w||(this.i=a,t1(this),v1(this,a),o1(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.h.hB=function(){if(this.w){a1(this.context.logger,w1(this).tc.close);var a=g.UA();a&&this.R&&g.NA(a,this.R);p1(this)}};
g.h.uB=function(){g.K(this.B,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.h.dD=function(){var a=g.UA(),b=w1(this);b=b?b.Rc:this.G;a&&b&&s0(a,[b])};
g.h.cD=function(){var a=g.UA(),b=w1(this);b=b?b.Rc:this.G;a&&b&&t0(a,[b])};
g.h.gD=function(){var a=w1(this);a1(this.context.logger,a.tc.mz);var b=g.UA();b&&a&&s0(b,[a.Cd,a.Rc])};
g.h.fD=function(){var a=g.UA(),b=w1(this);a&&b&&t0(a,[b.Cd])};
g.h.eD=function(a){var b=w1(this),c=g.UA();this.i?a?(a=this.context.logger,a1(a,b.tc.Cn),a.g.sendVideoStatsEngageEvent(4,void 0),c&&b.Cd&&g.NA(c,b.Cd)):(a=this.context.logger,a1(a,b.tc.Cn),a.g.sendVideoStatsEngageEvent(4,void 0),c&&b.Rc&&g.NA(c,b.Rc)):(a=this.context.logger,a1(a,b.tc.Cn),a.g.sendVideoStatsEngageEvent(4,void 0),c&&this.G&&g.NA(c,this.G))};g.r(x1,l1);x1.prototype.mk=function(){l1.prototype.mk.call(this);Uoa(this)};
x1.prototype.show=function(){l1.prototype.show.call(this);var a=g.UA(),b=this.annotation.data;a&&b&&(b=b.session_data)&&s0(a,[g.yA(b.itct)])};
x1.prototype.hide=function(){l1.prototype.hide.call(this);var a=g.UA(),b=this.annotation.data;a&&b&&(b=b.session_data)&&t0(a,[g.yA(b.itct)])};g.r(y1,x1);g.h=y1.prototype;g.h.qL=function(a,b,c,d){this.o.stop();if(!this.u){var e=g.sg(a);this.i||(g.qg(a,e.width),g.qg(b,e.width));g.Zf(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.Zf(c,"right","1px");this.u=!0;g.tg(a,!0);this.w=new g.I(function(){g.J(this.g,"iv-branding-active")},0,this);
this.w.start()}};
g.h.FC=function(a,b){g.ln(this.g,"iv-branding-active");this.B=new g.I((0,g.x)(function(){g.tg(a,!1);this.i||g.qg(b,0)},this),250);
this.B.start();this.u=!1};
g.h.show=function(){if(!this.isActive){x1.prototype.show.call(this);if(!this.C){g.J(this.g,"iv-branding");var a=this.annotation.data;this.l=g.Pd("IMG",{"aria-label":"Channel watermark",src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.tg(this.l,!1);var b=g.Pd("DIV","branding-img-container",this.l);this.g.appendChild(b);(b=Z0(this.annotation))&&this.wi(this.l,b,this.annotation.id,a.session_data);if(a.channel_name){var c=g.Pd("DIV","iv-branding-context-name");
g.$d(c,a.channel_name);var d=g.Pd("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.i=new g.kQ(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.Z),this.i.g(d);b=g.Pd("DIV","iv-branding-context-subscribe-caret");c=g.Pd("DIV","branding-context-container-inner",b,c,d);g.tg(c,!1);d=g.Pd("DIV","branding-context-container-outer",c);g.Zf(d,"right",
a.image_width+"px");this.g.appendChild(d);this.o=new g.I(g.Ra(this.FC,c,d),500,this);g.H(this,this.o);this.context.g.ea(this.g,"mouseover",(0,g.x)(this.qL,this,c,d,b,a.image_height));this.context.g.ea(this.g,"mouseout",(0,g.x)(this.o.start,this.o,void 0))}this.C=!0}g.tg(this.g,!0);this.isActive=!0;if(this.l){a=this.l;var e=void 0===e?0:e;b=g.kg(a);c=g.sg(a);b=(new g.Wf(b.x,b.y,c.width,c.height)).width;c=g.Fa(void 0)?void 0:b;g.gg(a,c);e=new D0(a,[c,a.offsetTop],[c-b-e,a.offsetTop],200,ooa);g.H(this,
e);this.context.l.ea(e,"begin",g.Ra(g.tg,a,!0));e.play()}}};
g.h.hide=function(){this.isActive&&(x1.prototype.hide.call(this),g.tg(this.g,!1),this.isActive=!1)};
g.h.destroy=function(){this.i&&(this.i.dispose(),this.i=null);x1.prototype.destroy.call(this)};g.r(z1,x1);g.h=z1.prototype;g.h.show=function(){this.isActive||(x1.prototype.show.call(this),this.I||(Voa(this),this.I=!0),g.tg(this.g,!0),g.hl(function(){g.ln(this.g,"iv-promo-inactive")},100,this),this.g.removeAttribute("aria-hidden"),this.isActive=!0,C1(this),B1(this),D1(this,this.C))};
g.h.hide=function(){this.isActive&&(g.J(this.g,"iv-promo-inactive"),this.isActive=!1,this.g.setAttribute("aria-hidden",!0))};
g.h.lm=function(a,b,c,d,e,f){return this.w?!1:x1.prototype.lm.call(this,a,b,c,d,e,f)};
g.h.pp=function(a,b){b.stopPropagation();B1(this);D1(this,a);this.i.focus()};
g.h.kC=function(a){this.G=!0;this.pp(500,a)};
g.h.jC=function(){this.G=!1;A1(this)};
g.h.cC=function(a){a.stopPropagation();this.hide()};
g.h.dC=function(a){a.stopPropagation();C1(this);this.w=!0;g.J(this.g,"iv-promo-collapsed-no-delay");this.B.start()};
g.h.destroy=function(){this.B.dispose();x1.prototype.destroy.call(this)};g.r(E1,g.aP);g.h=E1.prototype;g.h.xc=function(a,b){if(!G1(this.player.L().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.rZ(b);c&&K1(this,c);return!0;case "removeCustomAnnotationById":return b&&this.g&&(u1(this.g,b),r0(this.player)),!0}return null};
g.h.getOptions=function(){return G1(this.player.L().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.an=function(){if(this.o){var a=g.mK(this.player).getVideoContentRect(!0);g.rg(this.o.element,a.width,a.height);g.gg(this.o.element,a.left,a.top)}if(this.g){var b=g.uK(this.player);a=this.g;b=b.width;g.K(a.B,"iv-drawer-small",426>=b);g.K(a.B,"iv-drawer-big",1280<=b)}};
g.h.UI=function(a){this.fc(a.state);g.R(a.state,2)&&(this.Ij()&&this.cw()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.bq(!1))};
g.h.load=function(){g.aP.prototype.load.call(this);this.fc(g.lK(this.player));this.D++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.HH,this,b,this.D),d=(0,g.x)(function(){this.w=null},this);
g.Xo()&&(c=L1(this,c));c={format:"XML",Xc:c,onError:d,od:{}};a.isPharma&&(c.od.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.L().C.get(b))&&M1(c,b);b=b&&(b.tl||b.sl);if(!a.dl||b)a.Ed?H1(this,a.Ed,c):(this.l=(0,g.x)(this.yD,this,c),this.player.addEventListener("videodatachange",this.l));g.DK(this.player,this.o.element,4);this.an();(b=a.Fa&&a.Fa.cards&&a.Fa.cards.cardCollectionRenderer||null)&&$oa(this,b);(b=moa(a))&&apa(this,b,a.videoId||null,a.eventId||null)};
g.h.fc=function(a){a=!a.isCued()&&!g.R(a,1024);g.Au(this.i,a);g.Au(this.o,a)};
g.h.yD=function(a){var b=this.player.getVideoData();b.Ed&&(this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null),H1(this,b.Ed,a))};
g.h.unload=function(){g.eQ(this.player.app,"annotations_module",void 0);g.Mb(this.B,function(a){a.destroy()});
this.C=null;this.g&&(this.g.destroy(),this.g=null,r0(this.player));this.G=!1;this.w&&(this.w.abort(),this.w=null);this.B={};this.i.hide();g.aP.prototype.unload.call(this);g.zu(this.o);this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null)};
g.h.HH=function(a,b,c){this.w=null;!J1(this,b,a)&&(a=g.up(c)&&c.responseXML?c.responseXML:null)&&(K1(this,a),g.J(this.player.getRootNode(),"iv-module-loaded"))};
g.h.dy=function(a){a==this.player.getVideoData().videoId&&(this.loaded?Xoa(this):this.load())};
g.h.Ij=function(){return!!this.g&&this.g.isAvailable()};
g.h.cw=function(){this.Ij();return!!this.g&&this.g.w};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Ij();this.g&&(a?c?o1(this.g,c,b):o1(this.g,"YOUTUBE_DRAWER_AUTO_OPEN",b):p1(this.g))};
g.h.bq=function(a,b){this.player.N(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.V=function(){this.player.L().C.unsubscribe("vast_info_card_add",this.dy,this);g.ln(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.I,b=0,c=a.length;b<c;b++)g.Yo(a[b]);this.I.length=0;g.aP.prototype.V.call(this)};g.oP.annotations_module=E1;g.oP.creatorendscreen=H0;})(_yt_player);
