(function(g){var window=this;var z3=function(a,b,c){var d=b.ra();g.K(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.kc(c?c:"mqdefault.jpg");var f=b instanceof g.LB&&b.lengthSeconds?g.lL(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.BD(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.LB?b.na:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.Mi||g.WL("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.Jh(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.DD&&(d.playlist_length=b.getLength());a.update(d)},A3=function(a,b){g.Bu.call(this,{A:"div",
U:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},B3=function(a){g.T.call(this,{A:"div",
U:["ytp-upnext","ytp-player-content"],K:{"aria-label":"{{aria_label}}"},H:[{A:"div",F:"ytp-cued-thumbnail-overlay-image",K:{style:"{{background}}"}},{A:"span",F:"ytp-upnext-top",H:[{A:"span",F:"ytp-upnext-header",T:"Up Next"},{A:"span",F:"ytp-upnext-title",T:"{{title}}"},{A:"span",F:"ytp-upnext-author",T:"{{author}}"}]},{A:"a",F:"ytp-upnext-autoplay-icon",K:{role:"button",href:"{{url}}","aria-label":"Play next video"},H:[{A:"svg",K:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},H:[{A:"circle",
F:"ytp-svg-autoplay-circle",K:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{A:"circle",F:"ytp-svg-autoplay-ring",K:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{A:"path",F:"ytp-svg-fill",K:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{A:"span",F:"ytp-upnext-bottom",H:[{A:"span",F:"ytp-upnext-cancel"},{A:"span",F:"ytp-upnext-paused",T:"Autoplay is paused"}]}]});
this.w=null;var b=this.i["ytp-upnext-cancel"];this.w=new g.T({A:"button",U:["ytp-upnext-cancel-button","ytp-button"],K:{tabindex:"0","aria-label":"Cancel autoplay"},T:"Cancel"});g.H(this,this.w);this.w.ea("click",this.cH,this);this.w.g(b);this.l=a;this.I=this.i["ytp-svg-autoplay-ring"];this.C=this.B=this.o=this.u=null;this.D=new g.I(this.wl,5E3,this);g.H(this,this.D);this.G=0;this.J(this.i["ytp-upnext-autoplay-icon"],"click",this.OI);this.tx();this.J(a,"autonavvisibility",this.tx);this.J(a,"mdxnowautoplaying",
this.gI);this.J(a,"mdxautoplaycanceled",this.hI);this.J(a,"mdxautoplayupnext",this.Iz);3==this.l.getPresentingPlayerType()&&(a=(a=g.nK(g.gK(this.l)))?a.TB():null)&&this.Iz(a)},C3=function(a,b){if(!a.o){g.Mo("a11y-announce","Up Next "+a.u.title);
a.G=(0,g.Lq)();a.o=new g.I((0,g.x)(a.no,a,b),25);a.no(b);var c=b||g.Q(a.l.L().experiments,"autoplay_time")||1E4;a.l.ha("onAutonavCoundownStarted",c)}g.ln(a.element,"ytp-upnext-autoplay-paused")},E3=function(a){D3(a);
a.G=(0,g.Lq)();a.no();g.J(a.element,"ytp-upnext-autoplay-paused")},D3=function(a){a.o&&(a.o.dispose(),a.o=null)},F3=function(a,b){b=void 0===b?!1:b;
if(g.P(a.l.L().experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.u.ra(),a.wl(),a.B=new Notification("Up Next",{body:c.title,icon:c.kc()}),a.C=a.J(a.B,"click",a.FI),a.D.start())}D3(a);a.l.nextVideo(!1,b)},G3=function(a){A3.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.l=new g.T({A:"div",F:"ytp-subscribe-card",H:[{A:"img",F:"ytp-author-image",K:{src:b.Od}},{A:"div",F:"ytp-subscribe-card-right",H:[{A:"div",F:"ytp-author-name",T:b.author},{A:"div",F:"html5-subscribe-button-container"}]}]});g.H(this,this.l);this.l.g(this.element);this.o=new g.kQ("Subscribe",null,"Unsubscribe",null,!0,!1,b.Gf,b.subscribed,"trailer-endscreen",null,null,a);g.H(this,this.o);this.o.g(this.l.i["html5-subscribe-button-container"]);this.hide()},H3=function(a){var b=
a.L(),c=g.Js||g.bg?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.T.call(this,{A:"a",U:e,K:{href:"{{url}}",target:d?b.o:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},H:[{A:"div",F:"ytp-videowall-still-image",K:{style:"{{background}}"}},{A:"span",F:"ytp-videowall-still-info",H:[{A:"span",F:"ytp-videowall-still-info-bg",H:[{A:"span",F:"ytp-videowall-still-info-content",K:c,H:[{A:"span",F:"ytp-videowall-still-info-title",T:"{{title}}"},{A:"span",F:"ytp-videowall-still-info-author",
T:"{{author_and_views}}"},{A:"span",F:"ytp-videowall-still-info-live",T:"Live"},{A:"span",F:"ytp-videowall-still-info-duration",T:"{{duration}}"}]}]}]},{A:"span",U:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],H:[{A:"span",F:"ytp-videowall-still-listlabel-icon"},"Playlist",{A:"span",F:"ytp-videowall-still-listlabel-length",H:[" (",{A:"span",T:"{{playlist_length}}"},")"]}]},{A:"span",U:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],H:[{A:"span",F:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{A:"span",F:"ytp-videowall-still-listlabel-length",T:" (50+)"}]}]});this.w=d;this.l=a;this.o=null;this.u=new g.Qs(this);g.H(this,this.u);this.ea("click",this.C);this.ea("keypress",this.D);this.u.J(a,"videodatachange",this.B);g.GK(a,this.element,this);this.B()},I3=function(a){g.IK(a.l,a.element);
var b=a.o.ra().videoId,c=a.o.getPlaylistId();g.HS(a.l.app,b,a.o.Gb,c,void 0,void 0)},J3=function(a){A3.call(this,a,"videowall-endscreen");
this.B=a;this.w=0;this.o=[];this.C=this.O=this.u=null;this.D=this.P=!1;this.M=null;this.ba=new g.Qs(this);g.H(this,this.ba);this.G=new g.I(g.Ra(g.J,this.element,"ytp-show-tiles"),0);g.H(this,this.G);var b=new g.T({A:"button",U:["ytp-button","ytp-endscreen-previous"],K:{"aria-label":"Previous"},H:[g.tL()]});g.H(this,b);b.g(this.element);b.ea("click",this.uE,this);this.I=new g.vu({A:"div",F:"ytp-endscreen-content"});g.H(this,this.I);this.I.g(this.element);b=new g.T({A:"button",U:["ytp-button","ytp-endscreen-next"],
K:{"aria-label":"Next"},H:[g.uL()]});g.H(this,b);b.g(this.element);b.ea("click",this.tE,this);this.l=new B3(a);g.H(this,this.l);g.DK(this.player,this.l.element,4);this.hide()},K3=function(a){return g.EK(a.player)&&a.ot()&&!a.C},L3=function(a,b){return(0,g.fe)(b.suggestions,function(c){c=g.XL(a.B.L(),c);
g.H(a,c);return c})},M3=function(a){var b=a.jq();
b!=a.P&&(a.P=b,a.player.N("autonavvisibility"))},O3=function(a){g.aP.call(this,a);
this.g=null;this.i=new g.Qs(this);g.H(this,this.i);this.l=a.L();N3(a)?this.g=new J3(this.player):this.l.Ga?this.g=new G3(this.player):this.g=new A3(this.player);g.H(this,this.g);g.DK(this.player,this.g.element,4);this.Oy();this.i.J(a,"videodatachange",this.Oy,this);this.i.J(a,g.AD("endscreen"),this.CD,this);this.i.J(a,"crx_endscreen",this.DD,this)},N3=function(a){a=a.L();
return a.Ca&&!a.Ga};
g.r(A3,g.Bu);A3.prototype.create=function(){this.created=!0};
A3.prototype.destroy=function(){this.created=!1};
A3.prototype.ot=function(){return!1};
A3.prototype.jq=function(){return!1};g.r(B3,g.T);g.h=B3.prototype;g.h.wl=function(){this.B&&(this.D.stop(),this.Sa(this.C),this.C=null,this.B.close(),this.B=null)};
g.h.tx=function(){g.Au(this,g.hK(this.l))};
g.h.FI=function(){window.focus();this.wl()};
g.h.hide=function(){g.T.prototype.hide.call(this)};
g.h.no=function(a){a=a||g.Q(this.l.L().experiments,"autoplay_time")||1E4;var b=Math.min((0,g.Lq)()-this.G,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.getPresentingPlayerType()?F3(this,!0):this.o&&this.o.start()};
g.h.OI=function(a){!g.Zd(this.w.element,g.ar(a))&&g.dM(a,this.l)&&F3(this)};
g.h.cH=function(){g.jK(this.l,!0)};
g.h.gI=function(a){this.l.getPresentingPlayerType();this.show();C3(this,a)};
g.h.Iz=function(a){this.l.getPresentingPlayerType();this.u&&this.u.ra().videoId==a.ra().videoId||(this.u=a,z3(this,a,"hqdefault.jpg"))};
g.h.hI=function(){this.l.getPresentingPlayerType();D3(this);this.hide()};
g.h.V=function(){D3(this);this.wl();g.T.prototype.V.call(this)};g.r(G3,A3);g.r(H3,g.T);H3.prototype.C=function(a){g.dM(a,this.l,this.w,this.o.Gb||void 0)&&I3(this)};
H3.prototype.D=function(a){switch(a.keyCode){case 13:case 32:g.fr(a)||(I3(this),g.er(a))}};
H3.prototype.B=function(){var a=this.l.getVideoData(),b=this.l.L();this.w=a.ac?!1:b.i};g.r(J3,A3);g.h=J3.prototype;g.h.create=function(){A3.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.u=L3(this,a),this.O=a);this.Ef();this.ba.J(this.player,"appresize",this.Ef);this.ba.J(this.player,"onVideoAreaChange",this.Ef);this.ba.J(this.player,"videodatachange",this.vE);this.ba.J(this.player,"autonavchange",this.kq);this.ba.J(this.player,"autonavcancel",this.sE);a=this.O.autonavState;a!=this.M&&this.kq(a);this.ba.J(this.element,"transitionend",this.fK)};
g.h.destroy=function(){g.Ss(this.ba);g.Di(this.o);this.o=[];this.u=null;A3.prototype.destroy.call(this);g.ln(this.element,"ytp-show-tiles");this.G.stop();this.M=this.O.autonavState};
g.h.ot=function(){return 1!=this.O.autonavState};
g.h.show=function(){A3.prototype.show.call(this);g.ln(this.element,"ytp-show-tiles");this.player.L().g?g.cn(this.G):this.G.start();(this.D||this.C&&this.C!=this.O.clientPlaybackNonce)&&g.jK(this.player,!1);K3(this)?(M3(this),2==this.O.autonavState?g.P(this.player.L().experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?F3(this.l,!0):C3(this.l):3==this.O.autonavState&&E3(this.l)):(g.jK(this.player,!0),M3(this))};
g.h.hide=function(){A3.prototype.hide.call(this);E3(this.l);M3(this)};
g.h.fK=function(a){g.ar(a)==this.element&&this.Ef()};
g.h.Ef=function(){if(this.u&&this.u.length){g.J(this.element,"ytp-endscreen-paginate");var a=g.uK(this.B,!0,this.B.isFullscreen()),b=g.RC(this.B);b&&(b=b.Zb()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.u.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,t=e/2,v=b<=f-2&&n>=t*m,y=e<=k-2&&n>=q*m;if((q+1)/t*d/c>c/(q/(t+1)*d)&&y)n-=q*m,e+=2;else if(v)n-=t*m,b+=2;else if(y)n-=
q*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.od(a.width/m||1,1,1.21);n*=g.od(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.I.element;g.rg(a,m,n);g.Zf(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.l;f=this.u[0];c.u=f;z3(c,f,"hqdefault.jpg");g.K(this.element,"ytp-endscreen-takeover",K3(this));M3(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=
c,t=0,d&&f>=b-2&&k>=e-2?t=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(t=2):t=2),q=g.pd(q+this.w,l),0!=t){v=this.o[c];v||(v=new H3(this.player),this.o[c]=v,a.appendChild(v.element));y=Math.floor(n*k/e);var B=Math.floor(m*f/b),C=Math.floor(n*(k+t)/e)-y-4,G=Math.floor(m*(f+t)/b)-B-4;g.gg(v.element,B,y);g.rg(v.element,G,C);g.Zf(v.element,"transitionDelay",(k+f)/20+"s");g.K(v.element,"ytp-videowall-still-mini",1==t);g.K(v.element,"ytp-videowall-still-large",2<t);t=v;q=this.u[q];t.o!=q&&(t.o=q,z3(t,q,g.jn(t.element,
"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg"),(q=(q=q.Gb)&&q.itct)&&g.HK(t.l,t.element,q));c++}g.K(this.element,"ytp-endscreen-paginate",c<l);for(b=this.o.length-1;b>=c;b--)e=this.o[b],g.Vd(e.element),g.Ci(e);this.o.length=c}};
g.h.vE=function(){var a=this.player.getVideoData();this.O!=a&&(this.w=0,this.u=L3(this,a),this.O=a,this.Ef())};
g.h.tE=function(){this.w+=this.o.length;this.Ef()};
g.h.uE=function(){this.w-=this.o.length;this.Ef()};
g.h.VC=function(){return!!this.l.o};
g.h.kq=function(a){1==a?(this.D=!1,this.C=this.O.clientPlaybackNonce,D3(this.l),this.Da()&&this.Ef()):(this.D=!0,this.Da()&&K3(this)&&(2==a?C3(this.l):3==a&&E3(this.l)))};
g.h.sE=function(a){if(a){for(a=0;a<this.o.length;a++)g.JK(this.B,this.o[a].element,!0);this.kq(1)}else this.C=null,this.D=!1;this.Ef()};
g.h.jq=function(){return this.Da()&&K3(this)};g.r(O3,g.aP);g.h=O3.prototype;g.h.gw=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!N3(this.player)||b;a=a.uh||g.$y(a.La);var c=g.cS(this.player.app);return b&&!a&&!c};
g.h.ew=function(){return this.g.jq()};
g.h.OC=function(){return this.ew()?this.g.VC():!1};
g.h.V=function(){g.eQ(this.player.app,"endscreen",void 0);g.aP.prototype.V.call(this)};
g.h.load=function(){g.aP.prototype.load.call(this);this.g.show()};
g.h.unload=function(){g.aP.prototype.unload.call(this);this.g.hide();this.g.destroy()};
g.h.CD=function(a){this.gw()&&(this.g.created||this.g.create(),"load"==a.getId()&&this.load())};
g.h.DD=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.Oy=function(){g.eQ(this.player.app,"endscreen",void 0);var a=this.player.getVideoData();a=new g.xD(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});g.H(this,a);var b=new g.xD(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.H(this,b);g.zK(this.player,[a,b])};g.oP.endscreen=O3;})(_yt_player);
